# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c81d6d371b7df60749477a5ab40e0415005f0dfaedea62841fb3c9dc848a6dfcfb61135400d6c5bac4d15ae4ffa7f21de541cbd9129d06252fcba229f0ff414

test:
  secret_key_base: 6a5328dfbfc7ff3aaa383af90b29b42107abcd4fe7da1ae62162bab96ab82a8cdf000326beb4f713baf79505585955448581a48f78bf0fa647df62a2e3849c1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
